ARG DOCKER_OPENRESTY_SUFFIX
ARG DOCKER_REPOSITORY

FROM ${DOCKER_REPOSITORY}:test-${DOCKER_OPENRESTY_SUFFIX}

RUN rm -rf /usr/local/bin/kong

ENV KONG_GO_PLUGINSERVER_VERSION=master
ENV GOPATH=/tmp/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN rm -rf /tmp/go/src/github.com/kong/ || true \
    && mkdir -p /tmp/go/src/github.com/kong/ \
    && git clone --branch ${KONG_GO_PLUGINSERVER_VERSION} https://github.com/Kong/go-pluginserver.git /tmp/go/src/github.com/kong/go-pluginserver \
    && cd /tmp/go/src/github.com/kong/go-pluginserver \
    && go mod tidy

COPY kong /kong
RUN mkdir -p /kong/servroot/logs
RUN chmod -R 777 /kong
WORKDIR /kong
RUN make dev  

RUN rm -rf /tmp/build

CMD ["sh", "-c", "cat /kong/spec/fixtures/hosts >> /etc/hosts; tail -f /dev/null"]
