ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="xenial"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

ARG KONG_VERSION="0.0.0"
ARG KONG_PACKAGE_NAME="kong"
ARG KONG_UID="1337"
ARG USER="kong"
ARG RUNAS_USER="root"

ARG SU_EXEC_VERSION=0.2
ARG SU_EXEC_URL="https://github.com/ncopa/su-exec/archive/v${SU_EXEC_VERSION}.tar.gz"

RUN apt-get update && apt-get install -y perl curl gcc build-essential libcap2-bin unzip 

RUN curl -sL "${SU_EXEC_URL}" | tar -C /tmp -zxf - \
  && make -C "/tmp/su-exec-${SU_EXEC_VERSION}" \
  && cp "/tmp/su-exec-${SU_EXEC_VERSION}/su-exec" /usr/bin

RUN adduser --uid ${KONG_UID} ${USER} \
  && mkdir -p "/usr/local/kong"

ARG RESTY_IMAGE_TAG=kong-ubuntu-xenial
ENV RESTY_IMAGE_TAG $RESTY_IMAGE_TAG
COPY output/${KONG_PACKAGE_NAME}-${KONG_VERSION}.${RESTY_IMAGE_TAG}.amd64.deb /kong.deb

RUN dpkg -i /kong.deb

RUN if [ "$KONG_UID" != "1337" ] ; then chown -R ${USER}:0 /usr/local/kong \
  && chmod -R g=u /usr/local/kong \
  && chmod -R 777 /usr/local/lib \
  && chmod -R 777 /usr/local/share \
  && chmod -R 777 /usr/local/bin ; fi

COPY test/docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

USER $RUNAS_USER

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]
