ARG RESTY_IMAGE_BASE="centos"
ARG RESTY_IMAGE_TAG="7"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

ARG KONG_VERSION="0.0.0"
ARG KONG_PACKAGE_NAME="kong"
ARG RESTY_IMAGE_TAG

ARG SU_EXEC_VERSION=0.2
ARG SU_EXEC_URL="https://github.com/ncopa/su-exec/archive/v${SU_EXEC_VERSION}.tar.gz"

ARG REDHAT_USERNAME
ARG REDHAT_PASSWORD
ARG RHEL="false"

RUN if [ "$RHEL" = "true" ] ; then yum -y install --disableplugin=subscription-manager perl perl-Time-HiRes gcc make unzip tar gzip shadow-utils hostname unzip ; fi

RUN if [ "$RHEL" = "false" ] ; then yum -y install perl perl-Time-HiRes gcc make unzip tar gzip shadow-utils hostname unzip ; fi

RUN curl -sL "${SU_EXEC_URL}" | tar -C /tmp -zxf - \
  && make -C "/tmp/su-exec-${SU_EXEC_VERSION}" \
  && cp "/tmp/su-exec-${SU_EXEC_VERSION}/su-exec" /usr/bin \
  && useradd --uid 1337 kong

COPY output/kong.rpm /kong.rpm
RUN rpm -i kong.rpm

COPY test/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]