ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="xenial"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

ARG KONG_VERSION="0.0.0"
ARG KONG_PACKAGE_NAME="kong"
ARG RESTY_IMAGE_TAG

ARG SU_EXEC_VERSION=0.2
ARG SU_EXEC_URL="https://github.com/ncopa/su-exec/archive/v${SU_EXEC_VERSION}.tar.gz"

RUN apt-get update && apt-get install -y perl curl gcc build-essential libcap2-bin

RUN curl -sL "${SU_EXEC_URL}" | tar -C /tmp -zxf - \
  && make -C "/tmp/su-exec-${SU_EXEC_VERSION}" \
  && cp "/tmp/su-exec-${SU_EXEC_VERSION}/su-exec" /usr/bin \
  && useradd --uid 1337 kong

COPY output/${KONG_PACKAGE_NAME}-${KONG_VERSION}.${RESTY_IMAGE_TAG}.all.deb /kong.deb

RUN dpkg -i kong.deb

COPY test/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]