FROM alpine:3.6
LABEL maintainer="Kong Core Team <team-core@konghq.com>"

RUN apk add --no-cache --virtual .build-deps tar ca-certificates \
	&& apk add --no-cache libgcc openssl pcre perl tzdata

COPY kong.apk.tar.gz kong.apk.tar.gz

RUN tar -xzf kong.apk.tar.gz -C /tmp \
	&& rm -f kong.tar.gz \
	&& cp -R /tmp/usr / \
	&& rm -rf /tmp/usr \
	&& cp -R /tmp/etc / \
	&& rm -rf /tmp/etc \
	&& apk del .build-deps

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]