FROM ubuntu:xenial

ARG KONG_VERSION="0.0.0"
ARG KONG_PACKAGE_NAME="kong-community-edition"
ARG RESTY_IMAGE_TAG="xenial"

RUN apt-get update && apt-get install -y perl

COPY output/${KONG_PACKAGE_NAME}-${KONG_VERSION}.${RESTY_IMAGE_TAG}.all.deb /kong.deb

RUN dpkg -i kong.deb

COPY test/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]