version: '2.1'
services:
  kong:
    image: kong:development
    entrypoint: tail -f /dev/null
    working_dir: /kong
    volumes:
      - ../kong:/kong
      - ./kong-plugin:/kong-plugin
    depends_on:
      db:
        condition: service_healthy
    environment:
      LUA_PATH: /kong-plugin/?.lua;;
      KONG_PREFIX: /kong/servroot
      KONG_PLUGINS: bundled,myplugin
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_PG_HOST: db
      KONG_TEST_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_ANONYMOUS_REPORTS: "false"
    links:
      - db:db
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    restart: on-failure
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong_tests}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
