version: '2.1'
services:
  kong:
    image: kong/kong-build-tools:test
    privileged: true
    network_mode: host
    environment:
      TEST_SUITE: ${TEST_SUITE:-unit}
      KONG_DATABASE: postgres
      KONG_TEST_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_TEST_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_PG_HOST: 127.0.0.1
      KONG_TEST_PG_HOST: 127.0.0.1
      KONG_PATH: /kong
      KONG_TEST_PATH: /kong
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_TEST_PG_USER: ${KONG_PG_USER:-kong}
      KONG_ANONYMOUS_REPORTS: "false"
    network_mode: "host"
    restart: on-failure
  db:
    image: postgres:${POSTGRES_VERSION:-9.5}
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong_tests}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    restart: on-failure
    network_mode: "host"
    stdin_open: true
    tty: true