FROM ubuntu:xenial

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  ruby \
  ruby-dev \
  rubygems \
  lsb-release \
  libffi-dev \
  build-essential \
  rpm

RUN gem install --no-ri --no-rdoc fpm

COPY fpm-entrypoint.sh /fpm-entrypoint.sh

CMD ["/fpm-entrypoint.sh"]