version: '2.1'
services:
  kong:
    image: kong:development
    entrypoint: tail -f /dev/null
    user: ${USER:-root}
    working_dir: /kong
    volumes:
      - ../kong:/kong
      - ./kong-plugin:/kong-plugin
    depends_on:
      db:
        condition: service_healthy
    environment:
      LUA_PATH: /tmp/build/usr/local/share/lua/5.1/?.lua;/tmp/build/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/kong-plugin/?.lua;/kong/?.lua;;
      KONG_PREFIX: /kong/servroot
      KONG_PLUGINS: bundled,myplugin
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_TEST_DATABASE: postgres
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong_tests}
      KONG_PG_HOST: 127.0.0.1
      KONG_TEST_PG_HOST: 127.0.0.1
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_ANONYMOUS_REPORTS: "false"
    network_mode: "host"
    restart: on-failure
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong_tests}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    network_mode: "host"
    stdin_open: true
    tty: true
