ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="xenial"
ARG DOCKER_OPENRESTY_SUFFIX

FROM --platform=$BUILDPLATFORM kong/kong-build-tools:openresty-${RESTY_IMAGE_BASE}-${RESTY_IMAGE_TAG}-${DOCKER_OPENRESTY_SUFFIX} as BUILD

WORKDIR /kong
COPY kong /kong
COPY build-kong.sh /build-kong.sh

RUN /build-kong.sh
