# Dockerfile - Centos
# Centos base image with all prerequisites to compile / install openresty and Kong

ARG RESTY_IMAGE_BASE="centos"
ARG RESTY_IMAGE_TAG="7"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

RUN sed -i -e '2 i minrate=1' /etc/yum.conf
RUN yum clean all && yum update -y

RUN yum -y install wget tar readline-devel pcre-devel openssl-devel gcc curl unzip \
  zlib-devel make gcc gcc-c++ bzip2 patch perl m4 git
