# Dockerfile - Centos
# Centos base image with all prerequisites to compile / install openresty and Kong

ARG RESTY_IMAGE_BASE="centos"
ARG RESTY_IMAGE_TAG="7"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

RUN yum update -y && \
  yum -y install ca-certificates wget tar readline-devel pcre-devel openssl-devel \
  gcc curl unzip zlib-devel cmake make gcc gcc-c++ bzip2 patch perl m4 git
