ARG RESTY_IMAGE_BASE="ubuntu"
ARG RESTY_IMAGE_TAG="xenial"
ARG DOCKER_KONG_SUFFIX
ARG KONG_SHA

FROM --platform=$TARGETPLATFORM kong/kong-build-tools:kong-packaged-${RESTY_IMAGE_BASE}-${RESTY_IMAGE_TAG}-${DOCKER_KONG_SUFFIX} as FPM

FROM  --platform=$TARGETPLATFORM scratch

COPY --from=FPM /output /output
