ARG RESTY_IMAGE_TAG="3.10"

FROM alpine:3.10

ARG YQ_VERSION=1.15.0

RUN apk update \
    && apk upgrade \
    && apk add --no-cache cmake gcc make g++ musl-dev pcre-dev \
        openssl-dev zlib-dev ncurses-dev readline-dev curl perl \
        libffi-dev libc-dev git unzip tar openssh m4 xz gnupg openssl musl \
        linux-headers bsd-compat-headers bash go wget shadow \
        ca-certificates wget coreutils patch grep sed \
    && curl -sSL https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64 -o /usr/local/bin/yaml \
    && chmod +x /usr/local/bin/yaml \
    && update-ca-certificates
