ARG PACKAGE_TYPE
ARG DOCKER_OPENRESTY_SUFFIX
ARG DOCKER_REPOSITORY

FROM ${DOCKER_REPOSITORY}:openresty-${PACKAGE_TYPE}-${DOCKER_OPENRESTY_SUFFIX}

WORKDIR /kong
COPY kong /kong
COPY build-kong.sh /build-kong.sh

RUN rm -rf /distribution/*

COPY kong/distribution /distribution
COPY kong/.requirements /distribution/.requirements
RUN cd /distribution && ./post-install.sh

RUN /build-kong.sh
