os: linux
dist: xenial
sudo: false

language: c

addons:
  apt:
    packages:
     - build-essential
     - perl
     - curl

compiler:
  - gcc
  - clang

services:
  - docker

env:
  global:
    - JOBS=2
    - WORK=$TRAVIS_BUILD_DIR/work
    - PREFIX=$HOME/kopenresty
    - LUAROCKS=3.1.3
    - PCRE=8.43
  matrix:
    - OPENRESTY=1.15.8.1 OPENSSL=1.1.1c
    - OPENRESTY=1.15.8.1 OPENSSL=1.1.1c NO_KONG_NGINX_MODULE=1
    - OPENRESTY=1.13.6.2 OPENSSL=1.1.1c
    - OPENRESTY=1.13.6.2 OPENSSL=1.1.0k
    - OPENRESTY=1.13.6.2 OPENSSL=1.0.2s NO_OPENRESTY_PATCHES=1
    - OPENRESTY=1.11.2.5 OPENSSL=1.0.2s NO_OPENRESTY_PATCHES=1

stages:
  - unit tests
  - test
  - osx

jobs:
 include:
   - stage: unit tests
     env: BASH=3
     script: docker run -it --rm -v $TRAVIS_BUILD_DIR:/openresty-build-tools:ro bash:$BASH bash -c "(set -e; for f in /openresty-build-tools/t/*.sh; do bash \$f; done)"
   - stage: unit tests
     env: BASH=4
     script: docker run -it --rm -v $TRAVIS_BUILD_DIR:/openresty-build-tools:ro bash:$BASH bash -c "(set -e; for f in /openresty-build-tools/t/*.sh; do bash \$f; done)"
   - stage: unit tests
     env: BASH=5
     script: docker run -it --rm -v $TRAVIS_BUILD_DIR:/openresty-build-tools:ro bash:$BASH bash -c "(set -e; for f in /openresty-build-tools/t/*.sh; do bash \$f; done)"
   - stage: osx
     compiler: gcc
     os: osx
     script: ./kong-ngx-build --work $WORK --prefix $PREFIX --openresty $OPENRESTY --openssl $OPENSSL --luarocks $LUAROCKS --pcre $PCRE >build.log 2>&1 || (cat build.log; exit 1)
   - stage: osx
     compiler: clang
     os: osx
     script: ./kong-ngx-build --work $WORK --prefix $PREFIX --openresty $OPENRESTY --openssl $OPENSSL --luarocks $LUAROCKS --pcre $PCRE >build.log 2>&1 || (cat build.log; exit 1)

install:
  - if [[ $NO_OPENRESTY_PATCHES == "1" ]]; then OPENRESTY_PATCHES=--no-openresty-patches; fi
  - if [[ $NO_KONG_NGINX_MODULE == "1" ]]; then KONG_NGINX_MODULE=--no-kong-nginx-module; fi
  - echo $OPENRESTY_PATCHES
  - echo $KONG_NGINX_MODULE

script:
  - ./kong-ngx-build --work $WORK --prefix $PREFIX --jobs $JOBS --openresty $OPENRESTY --openssl $OPENSSL --luarocks $LUAROCKS --pcre $PCRE $OPENRESTY_PATCHES $KONG_NGINX_MODULE >build.log 2>&1 || (cat build.log; exit 1)
  - export PATH=$PREFIX/openresty/bin:$PATH
  - export PATH=$PREFIX/luarocks/bin:$PATH
  - export PATH=$PREFIX/openssl/bin:$PATH
  - (openresty -v 2>&1 | grep -F -- "$OPENRESTY") || (openresty -v; exit 1)
  - (openssl version | grep -F -- "$OPENSSL") || (openssl version; exit 1)
  - (luarocks --version | grep -F -- "$LUAROCKS") || (luarocks --version; exit 1)
  - (luarocks config | grep -F -- "LUA = \"$PREFIX/openresty/luajit/bin/luajit\"") || (luarocks config; exit 1)
  - (luarocks config | grep -F -- "LUA_INCDIR = \"$PREFIX/openresty/luajit/include/luajit-2.1\"") || (luarocks config; exit 1)
  - (luarocks config | grep -F -- "LUA_LIBDIR = \"$PREFIX/openresty/luajit/lib\"") || (luarocks config; exit 1)
  - (ldd $(which openresty) | grep -E -- "libssl.*?$PREFIX") || (ldd $(which openresty); exit 1)
  - (ldd $(which openresty) | grep -E -- "libcrypto.*?$PREFIX") || (ldd $(which openresty); exit 1)
  - (ldd $(which openresty) | grep -E -- "libluajit.*?$PREFIX") || (ldd $(which openresty); exit 1)
  - (openresty -V 2>&1 | grep -F -- "--with-pcre=$WORK/pcre-$PCRE") || (openresty -V; exit 1)
  - if [[ $NO_OPENRESTY_PATCHES == "1" ]]; then [[ ! -f "$WORK/openresty-$OPENRESTY/bundle/.patch_applied" ]] || (echo "OpenResty patches mistakenly applied"; exit 1); fi
  - if [[ $NO_OPENRESTY_PATCHES != "1" ]]; then [[ -f "$WORK/openresty-$OPENRESTY/bundle/.patch_applied" ]] || (echo "OpenResty patches not applied"; exit 1); fi
  - if [[ $OPENSSL != 1.0.* && $NO_KONG_NGINX_MODULE != "1" ]]; then (openresty -V 2>&1 | grep lua-kong-nginx-module) || (echo "Kong Nginx module not built"; exit 1); fi
  - if [[ $OPENSSL != 1.0.* && $NO_KONG_NGINX_MODULE == "1" ]]; then ! (openresty -V 2>&1 | grep lua-kong-nginx-module) || (echo "Kong Nginx module mistakenly built"; exit 1); fi
  - openresty -V # for humans

cache:
  apt: true
